package nl.rivm.screenit.model.enums;

/*-
 * ========================LICENSE_START=================================
 * screenit-base
 * %%
 * Copyright (C) 2012 - 2025 Facilitaire Samenwerking Bevolkingsonderzoek
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * =========================LICENSE_END==================================
 */

public enum ClientGebeurtenisType
{

	ANTWOORDFORMULIER_ONTVANGEN,

	AFNAMEDATUM_INGEVULD,

	IFOBT_VERLOREN,

	UITSLAG_GECOMMUNICEERD,

	INTAKE_AFSPRAAK_GEMAAKT,

	INTAKE_AFSPRAAK_AFGEZEGD,

	INTAKE_AFSPRAAK_GEWIJZIGD,

	INTAKE_AFSPRAAK_NO_SHOW,

	HERAANMELDING,

	EENMALIGE_AFMELDING,

	DEFINITIEVE_AFMELDING,

	TIJDELIJKE_AFMELDING,

	BEZWAAR_GEMAAKT_GEBOORTELAND,

	BEZWAAR_INGETROKKEN_GEBOORTELAND,

	BEZWAAR_GEMAAKT_DOSSIERVOERING,

	BEZWAAR_INGETROKKEN_DOSSIERVOERING,

	BEZWAAR_GEMAAKT_COMMUNICATIEHUISARTS,

	BEZWAAR_INGETROKKEN_COMMUNICATIEHUISARTS,

	BEZWAAR_GEMAAKT_KWALITEITSBORGING,

	BEZWAAR_INGETROKKEN_KWALITEITSBORGING,

	BEZWAAR_GEMAAKT_WETENSCHAPPELIJKONDERZOEK,

	BEZWAAR_INGETROKKEN_WETENSCHAPPELIJKONDERZOEK,

	BEZWAAR_GEMAAKT_WETENSCHAPPELIJKONDERZOEK_LICHAAMSMATERIAAL,

	BEZWAAR_INGETROKKEN_WETENSCHAPPELIJKONDERZOEK_LICHAAMSMATERIAAL,

	BEZWAAR_GEMAAKT_DIGITALE_UITWISSELING_MET_HET_ZIEKENHUIS,

	BEZWAAR_INGETROKKEN_DIGITALE_UITWISSELING_MET_HET_ZIEKENHUIS,

	BEZWAAR_GEMAAKT_GEEN_SIGNALERING_VERWIJSADVIES,

	BEZWAAR_INGETROKKEN_GEEN_SIGNALERING_VERWIJSADVIES,

	CERVIX_UITSTEL,

	CERVIX_ZAS_AANGEVRAAGD,

	CERVIX_HERDRUK,

	CERVIX_UITSLAG_GECOMMUNICEERD,

	MAMMA_AFSPRAAK_GEMAAKT,

	MAMMA_AFSPRAAK_VERPLAATST,

	MAMMA_AFSPRAAK_GEANNULEERD,

	MAMMA_UITSTEL,

	MAMMA_OPEN_UITNODIGING,

}
