package nl.rivm.screenit.model.enums;

/*-
 * ========================LICENSE_START=================================
 * screenit-base
 * %%
 * Copyright (C) 2012 - 2023 Facilitaire Samenwerking Bevolkingsonderzoek
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * =========================LICENSE_END==================================
 */

import nl.rivm.screenit.model.dashboard.DashboardActieType;
import nl.rivm.screenit.model.dashboard.DashboardType;

public enum LogGebeurtenis
{
	INLOGGEN(Level.INFO),

	INLOGGEN_MISLUKT(Level.ERROR),

	SELECTIERONDE_GESTART(Level.INFO, DashboardType.CLIENT_SELECTIE, DashboardActieType.START),

	SELECTIERONDE_CAPACITEIT_VAN_LEEG_GEBIED_GAAT_VERLOREN(Level.WARNING, DashboardType.CLIENT_SELECTIE, DashboardActieType.OVERIG),

	SELECTIERONDE_BEEINDIGD(Level.INFO, DashboardType.CLIENT_SELECTIE, DashboardActieType.OVERIG),

	CERVIX_SELECTIE_GESTART(Level.INFO, DashboardType.CERVIX_SELECTIE, DashboardActieType.START),

	CERVIX_SELECTIE_BEEINDIGD(Level.INFO, DashboardType.CERVIX_SELECTIE, DashboardActieType.OVERIG),

	CERVIX_LKT_SELECTIE_GESTART(Level.INFO, DashboardType.CERVIX_SELECTIE, DashboardActieType.START),

	CERVIX_LKT_SELECTIE_BEEINDIGD(Level.INFO, DashboardType.CERVIX_SELECTIE, DashboardActieType.OVERIG),

	CERVIX_VERVOLGONDERZOEK_GESTART(Level.INFO, DashboardType.CERVIX_VERVOLGONDERZOEK, DashboardActieType.START),

	CERVIX_VERVOLGONDERZOEK_BEEINDIGD(Level.INFO, DashboardType.CERVIX_VERVOLGONDERZOEK, DashboardActieType.OVERIG),

	CERVIX_UITSTEL_GESTART(Level.INFO, DashboardType.CERVIX_UITSTEL, DashboardActieType.START),

	CERVIX_UITSTEL_BEEINDIGD(Level.INFO, DashboardType.CERVIX_UITSTEL, DashboardActieType.OVERIG),

	CERVIX_HERINNEREN_GESTART(Level.INFO, DashboardType.CERVIX_HERINNEREN, DashboardActieType.START),

	CERVIX_HERINNEREN_BEEINDIGD(Level.INFO, DashboardType.CERVIX_HERINNEREN, DashboardActieType.OVERIG),

	CERVIX_HEROVERWEGERS_BRIEVEN_GENEREREN_START(Level.INFO, DashboardType.CERVIX_HEROVERWEGERS, DashboardActieType.START),

	CERVIX_HEROVERWEGERS_BRIEVEN_GENEREREN_AFGEROND(Level.INFO, DashboardType.CERVIX_HEROVERWEGERS, DashboardActieType.OVERIG),

	CERVIX_MIGRANTEN_UITNODIGEN_GESTART(Level.INFO),

	CERVIX_MIGRANTEN_UITNODIGEN_AFGEROND(Level.INFO),

	CERVIX_DIGITAAL_LABFORMULIER_FOUT_ONTVANGEN(Level.WARNING, DashboardType.CERVIX_DIGITALE_LABFORMULIER_FOUT_BERICHTEN, DashboardActieType.OVERIG),

	CERVIX_DIGITAAL_LABFORMULIER_FOUT_ONTVANGEN_GECONTROLEERD(Level.INFO),

	CERVIX_DIGITAAL_LABFORMULIER_ONTVANGEN(Level.INFO),

	CERVIX_VERLATE_DEELNAME_COVID_GESTART(Level.INFO, DashboardType.CERVIX_VERLATE_DEELNAME_COVID19, DashboardActieType.START),

	CERVIX_CLIENT_GEEN_VERLATE_DEELNAME_UITNODIGING(Level.WARNING, DashboardType.CERVIX_VERLATE_DEELNAME_COVID19, DashboardActieType.OVERIG),

	CERVIX_VERLATE_DEELNAME_COVID_AFGEROND(Level.INFO, DashboardType.CERVIX_VERLATE_DEELNAME_COVID19, DashboardActieType.OVERIG),

	CERVIX_OUDE_NIET_INGESTUURDE_ZAS_GESTART(Level.INFO, DashboardType.CERVIX_OUDE_NIET_INGESTUURDE_ZAS, DashboardActieType.START),

	CERVIX_CLIENT_OUDE_NIET_INGESTUURDE_ZAS_HERINNERING(Level.INFO, DashboardType.CERVIX_OUDE_NIET_INGESTUURDE_ZAS, DashboardActieType.OVERIG),

	CERVIX_OUDE_NIET_INGESTUURDE_ZAS_AFGEROND(Level.INFO, DashboardType.CERVIX_OUDE_NIET_INGESTUURDE_ZAS, DashboardActieType.OVERIG),

	NIEUWE_IFOBT_AANGEVRAAGD(Level.INFO),

	BERICHT_MET_ZELFDE_ID(Level.INFO, DashboardType.VERSLAGEN, DashboardActieType.DAG),

	BERICHT_MET_ZELFDE_SETID_VERSIE(Level.INFO, DashboardType.VERSLAGEN, DashboardActieType.DAG),

	BERICHT_ONBEKENDE_BSN(Level.WARNING, DashboardType.VERSLAGEN, DashboardActieType.DAG),

	BERICHT_ONTVANGEN(Level.INFO, DashboardType.VERSLAGEN, DashboardActieType.DAG),

	BERICHT_VERWERKT(Level.INFO, DashboardType.VERSLAGEN, DashboardActieType.DAG),

	BERICHT_VERWERKT_MET_MELDING(Level.WARNING, DashboardType.VERSLAGEN, DashboardActieType.DAG),

	BERICHT_VERWERKT_MET_ERROR(Level.ERROR, DashboardType.VERSLAGEN, DashboardActieType.DAG),

	BERICHT_ONDANKS_BEZWAAR(Level.WARNING, DashboardType.VERSLAGEN, DashboardActieType.DAG),

	BERICHT_UITSLAG_VERVANGEN(Level.INFO, DashboardType.VERSLAGEN, DashboardActieType.DAG),

	BERICHT_PA_LAB_NAAR_PREV_RONDE(Level.INFO, DashboardType.VERSLAGEN, DashboardActieType.DAG),

	BERICHT_T_NUMMER_MISMATCH(Level.WARNING, DashboardType.VERSLAGEN, DashboardActieType.DAG),

	BRIEF_TOEGEVOEGD(Level.INFO),

	BRIEF_AFGEDRUKT(Level.INFO),

	BRIEF_DOORVOEREN(Level.INFO),

	BRIEF_TEGENHOUDEN(Level.INFO),

	BRIEF_HERDRUK(Level.INFO),

	IFOBT_HERINNERING_GESTART(Level.INFO, DashboardType.IFOBT_HERINNERING, DashboardActieType.START),

	IFOBT_HERINNERING_AFGEROND(Level.INFO, DashboardType.IFOBT_HERINNERING, DashboardActieType.OVERIG),

	MDL_VERSLAG_VAST(Level.INFO),

	MDL_VERSLAG_WIJZIG(Level.INFO),

	MDL_VERSLAG_VERWIJDERD(Level.INFO),

	MDL_VERSLAG_HEROPEND(Level.INFO),

	PA_VERSLAG_VAST(Level.INFO),

	PA_VERSLAG_WIJZIG(Level.INFO),

	PA_VERSLAG_VERWIJDERD(Level.INFO),

	PA_VERSLAG_HEROPEND(Level.INFO),

	ZOEKEN_CLIENT(Level.INFO),

	ZOEKEN_BEELDEN_CLIENT(Level.INFO),

	INZIEN_BEELDEN_CLIENT(Level.INFO),

	ZOEKEN_BEELDEN_PORTFOLIO(Level.INFO),

	INZIEN_BEELDEN_PORTFOLIO(Level.INFO),

	FOTOBESPREKING_BESPROKEN(Level.INFO),

	FOTOBESPREKING_OPNIEUW_BEOORDELEN(Level.INFO),

	FOTOBESPREKING_BEOORDELEN_ONGEDAAN_MAKEN(Level.INFO),

	CONCLUSIE_REVIEW_AFGEROND(Level.INFO),

	WIJZIG_TIJDELIJK_ADRES(Level.INFO),

	WIJZIG_AANHEF(Level.INFO),

	SCREENINGSRONDE_INZIEN(Level.INFO),

	CLIENTCONTACT_REGISTREREN(Level.INFO),

	DEELNAMEWENS_REGISTREREN(Level.INFO),

	ROOSTERBLOK_NIEUW(Level.INFO),

	ROOSTERBLOK_WIJZIG(Level.INFO),

	ROOSTERBLOK_VERWIJDEREN(Level.INFO),

	COLON_BLOKKADES_NIEUW(Level.INFO),

	COLON_BLOKKADES_WIJZIG(Level.INFO),

	COLON_BLOKKADES_VERWIJDEREN(Level.INFO),

	IFOBT_ONTVANGEN(Level.INFO),

	COLON_IFOBT_BERICHT_BINNENGEKOMEN(Level.INFO, DashboardType.COLON_IFOBT_KOPPELING, DashboardActieType.DAG),

	COLON_IFOBT_BERICHT_ERROR(Level.ERROR, DashboardType.COLON_IFOBT_KOPPELING, DashboardActieType.DAG),

	IFOBT_VERWERKT(Level.INFO),

	IFOBT_NIET_BEOORDEELBAAR(Level.INFO),

	RAPPEL_VERZONDEN(Level.INFO, DashboardType.IFOBT_HERINNERING, DashboardActieType.OVERIG),

	RONDE_VERLOPEN(Level.INFO, DashboardType.CLIENT_SELECTIE, DashboardActieType.OVERIG),

	COLON_GEMEENTE_NIET_GEKOPPELD_AAN_SCREENING_ORGANISATIE(Level.WARNING, DashboardType.CLIENT_SELECTIE, DashboardActieType.OVERIG),

	@Deprecated
	COLON_NO_SHOW_COLOSCOPIE_VASTGELEGD(Level.INFO),

	@Deprecated
	COLON_DEFINITIEF_VERVOLGBELEID_VASTGELEGD(Level.INFO),

	COLON_ILM_GESTART(Level.INFO, DashboardType.COLON_ILM, DashboardActieType.START),

	COLON_ILM_AFGEROND(Level.INFO, DashboardType.COLON_ILM, DashboardActieType.OVERIG),

	COLON_CONTROLE_MISSENDE_UITSLAGEN_GESTART(Level.INFO, DashboardType.COLON_CONTROLE_MISSENDE_UITSLAGEN, DashboardActieType.START),

	COLON_CONTROLE_MISSENDE_UITSLAGEN_MATCH(Level.WARNING, DashboardType.COLON_CONTROLE_MISSENDE_UITSLAGEN, DashboardActieType.OVERIG),

	COLON_CONTROLE_MISSENDE_UITSLAGEN_MATCH_GECONTROLEERD(Level.INFO),

	COLON_CONTROLE_MISSENDE_UITSLAGEN_AFGEROND(Level.INFO, DashboardType.COLON_CONTROLE_MISSENDE_UITSLAGEN, DashboardActieType.OVERIG),

	COLON_FEESTDAGEN_BEHEER(Level.INFO),

	CERVIX_CONTROLE_MISSENDE_UITSLAGEN_GESTART(Level.INFO, DashboardType.CERVIX_CONTROLE_MISSENDE_UITSLAGEN, DashboardActieType.START),

	CERVIX_CONTROLE_MISSENDE_UITSLAGEN_MATCH(Level.WARNING, DashboardType.CERVIX_CONTROLE_MISSENDE_UITSLAGEN, DashboardActieType.OVERIG),

	CERVIX_CONTROLE_MISSENDE_UITSLAGEN_MATCH_GECONTROLEERD(Level.INFO),

	CERVIX_CONTROLE_MISSENDE_UITSLAGEN_AFGEROND(Level.INFO, DashboardType.CERVIX_CONTROLE_MISSENDE_UITSLAGEN, DashboardActieType.OVERIG),

	ANTWOORDFORMULIER_ONTVANGEN(Level.INFO),

	ANTWOORDFORMULIER_CORRECTIE(Level.INFO),

	BERICHT_GEEN_PA_MDL_RELATIE(Level.INFO),

	CLIENT_CONTACT_GEGEVENS_GEWIJZIGD(Level.INFO),

	ROL_NIEUW(Level.INFO),

	ROL_WIJZIG(Level.INFO),

	ROL_VERWIJDEREN(Level.INFO),

	ROL_ACTIVEREN(Level.INFO),

	PARAMETERISATIE_WIJZIG(Level.WARNING),

	WACHTWOORD_GEWIJZIGD(Level.INFO),

	AANVRAGEN_ACCOUNT_MISLUKT(Level.INFO),

	WACHTWOORD_AANGEVRAAGD(Level.INFO),

	WACHTWOORD_GERESET(Level.INFO),

	MEDEWERKER_NIEUW(Level.INFO),

	MEDEWERKER_WIJZIG(Level.INFO),

	MEDEWERKER_INACTIVEERD(Level.INFO),

	MEDEWERKER_ACTIVEERD(Level.INFO),

	ORGANISATIE_MEDEWERKER_ONTKOPPEL(Level.INFO),

	ORGANISATIE_MEDEWERKER_KOPPEL(Level.INFO),

	ORGANISATIE_INACTIVEERD(Level.INFO),

	ORGANISATIE_ACTIVEERD(Level.INFO),

	ORGANISATIE_NIEUW(Level.INFO),

	ORGANISATIE_WIJZIG(Level.INFO),

	MAIL_QUEUE_VERSTUREN_MISLUKT(Level.WARNING, DashboardType.MAIL_LANDELIJK, DashboardActieType.DAG),

	MAIL_QUEUE_VERBINDING_HERSTELD(Level.INFO, DashboardType.MAIL_LANDELIJK, DashboardActieType.DAG),

	MAIL_QUEUE_ERG_GROOT(Level.WARNING, DashboardType.MAIL_LANDELIJK, DashboardActieType.DAG),

	MAIL_QUEUE_NORMAAL(Level.INFO, DashboardType.MAIL_LANDELIJK, DashboardActieType.DAG),

	GBA_IMPORT_GESTART(Level.INFO, DashboardType.GBA_LANDELIJK, DashboardActieType.START),

	GBA_IMPORT_AFGEROND(Level.INFO, DashboardType.GBA_LANDELIJK, DashboardActieType.OVERIG),

	GBA_IMPORT_GEEN_BSN(Level.WARNING, DashboardType.GBA_LANDELIJK, DashboardActieType.OVERIG),

	GBA_IMPORT_GEEN_GEBOORTEDATUM(Level.WARNING, DashboardType.GBA_LANDELIJK, DashboardActieType.OVERIG),

	GBA_IMPORT_VERWIJDERD_VAN_PERSOONSLIJST(Level.WARNING, DashboardType.GBA_LANDELIJK, DashboardActieType.OVERIG),

	INACTIEVE_CLIENT_INGEZIEN(Level.INFO),

	GBA_DASHBOARDMELDING_AFGEHANDELD(Level.INFO),

	GBA_IMPORT_BSN_NIET_OVEREEN(Level.WARNING, DashboardType.GBA_LANDELIJK, DashboardActieType.OVERIG),

	GBA_IMPORT_LANDCODE_TOEGEVOEGD(Level.INFO, DashboardType.GBA_LANDELIJK, DashboardActieType.OVERIG),

	GBA_IMPORT_NATIONALITEITCODE_TOEGEVOEGD(Level.INFO, DashboardType.GBA_LANDELIJK, DashboardActieType.OVERIG),

	GBA_IMPORT_GEMEENTE_TOEGEVOEGD(Level.WARNING, DashboardType.GBA_LANDELIJK, DashboardActieType.OVERIG),

	GBA_IMPORT_SKIP(Level.WARNING, DashboardType.GBA_LANDELIJK, DashboardActieType.OVERIG),

	GBA_IMPORT_FOUT(Level.ERROR, DashboardType.GBA_LANDELIJK, DashboardActieType.OVERIG),

	GBA_IMPORT_BEZWAAR(Level.INFO, DashboardType.GBA_LANDELIJK, DashboardActieType.OVERIG),

	GBA_IMPORT_HERACTIVATIE(Level.INFO, DashboardType.GBA_LANDELIJK, DashboardActieType.OVERIG),

	GBA_GEGEVENS_OPNIEUW_AANGEVRAAGD(Level.INFO, DashboardType.GBA_LANDELIJK, DashboardActieType.OVERIG),

	GBA_ADRES_NIET_GEWIJZIGD(Level.WARNING, DashboardType.GBA_LANDELIJK, DashboardActieType.OVERIG),

	GBA_ADRES_ONVOLLEDIG(Level.WARNING, DashboardType.GBA_LANDELIJK, DashboardActieType.OVERIG),

	GBA_PERSOONSGEGEVENS_NIET_GEWIJZIGD(Level.WARNING, DashboardType.GBA_LANDELIJK, DashboardActieType.OVERIG),

	GBA_OPHEFFEN_VERWIJDERINDICATIE(Level.INFO),

	GBA_PERSOONSGEGEVENS_NIEUW_AANVRAGEN_AFGEROND(Level.INFO, DashboardType.GBA_LANDELIJK, DashboardActieType.OVERIG),

	GBA_TIJDELIJK_ADRES(Level.INFO),

	GBA_ADHOC_IMPORT_TRANSGENDER(Level.WARNING, DashboardType.GBA_LANDELIJK, DashboardActieType.OVERIG),

	MEDVRY_VERSTUURD(Level.INFO),

	IFOBT_INLEZEN_GESTART(Level.INFO, DashboardType.IFOBT_INLEZEN, DashboardActieType.DAG),

	IFOBT_INLEZEN_AFGEROND(Level.INFO, DashboardType.IFOBT_INLEZEN, DashboardActieType.OVERIG),

	IFOBT_ONBEKENDE_BARCODE(Level.WARNING, DashboardType.IFOBT_INLEZEN, DashboardActieType.OVERIG),

	IFOBT_VERWERKING_GESTART(Level.INFO, DashboardType.IFOBT_VERWERKING, DashboardActieType.START),

	IFOBT_VERWERKING_AFGEROND(Level.INFO, DashboardType.IFOBT_VERWERKING, DashboardActieType.OVERIG),

	ANTWOORDFORMULIER_VERWERKING_GESTART(Level.INFO),

	ANTWOORDFORMULIER_VERWERKING_AFGEROND(Level.INFO),

	COLON_NA_GBA_VERWERKING_GESTART(Level.INFO, DashboardType.COLON_BATCH_NA_GBA_VERWERKING, DashboardActieType.START),

	COLON_NA_GBA_VERWERKING_AFGEROND(Level.INFO, DashboardType.COLON_BATCH_NA_GBA_VERWERKING, DashboardActieType.OVERIG),

	BRIEVEN_GENERENEN_GESTART(Level.INFO, DashboardType.BRIEVEN_GENEREREN, DashboardActieType.START),

	BRIEVEN_GENERENEN_AFGEROND(Level.INFO, DashboardType.BRIEVEN_GENEREREN, DashboardActieType.OVERIG),

	COLON_BRIEF_MERGE_FOUT(Level.WARNING, DashboardType.BRIEVEN_GENEREREN, DashboardActieType.OVERIG),

	BRIEVEN_CONTROLE(Level.INFO),

	IFOBT_KOPPELEN_GESTART(Level.INFO, DashboardType.TERUGKOPPELING_CLIENT_SELECTIE, DashboardActieType.START),

	IFOBT_KOPPELEN_AFGEROND(Level.INFO, DashboardType.TERUGKOPPELING_CLIENT_SELECTIE, DashboardActieType.OVERIG),

	IFOBT_CONTROLE_KOPPELEN_GESTART(Level.INFO, DashboardType.CONTROLE_TERUGKOPPELING_CLIENT_SELECTIE, DashboardActieType.START),

	IFOBT_CONTROLE_KOPPELEN_AFGEROND(Level.INFO, DashboardType.CONTROLE_TERUGKOPPELING_CLIENT_SELECTIE, DashboardActieType.OVERIG),

	IFOBT_CONTROLE_KOPPELEN_FOUT(Level.ERROR, DashboardType.CONTROLE_TERUGKOPPELING_CLIENT_SELECTIE, DashboardActieType.OVERIG),

	INTAKE_AFSPRAAK_MAKEN_GESTART(Level.INFO, DashboardType.INTAKE_AFSPRAAK_MAKEN, DashboardActieType.START),

	COLON_INTAKE_AFSPRAAK_BUITEN_MAX_AFSTAND(Level.WARNING, DashboardType.INTAKE_AFSPRAAK_MAKEN, DashboardActieType.OVERIG),

	INTAKE_AFSPRAAK_MAKEN_AFGEROND(Level.INFO, DashboardType.INTAKE_AFSPRAAK_MAKEN, DashboardActieType.OVERIG),

	COLON_HUISARTSBERICHTEN_OPNIEUW_VERSTUREN_GESTART(Level.INFO, DashboardType.COLON_HUISARTSBERICHTEN, DashboardActieType.START),

	COLON_HUISARTSBERICHTEN_OPNIEUW_VERSTUREN_AFGEROND(Level.INFO, DashboardType.COLON_HUISARTSBERICHTEN, DashboardActieType.OVERIG),

	COLON_HUISARTSBERICHTEN_NIET_VERZONDEN(Level.ERROR, DashboardType.COLON_HUISARTSBERICHTEN, DashboardActieType.DAG),

	UITROLLEN_GESTART(Level.INFO),

	UITROLLEN_AFGEROND(Level.INFO),

	AFSPRAAK_VERPLAATST(Level.INFO),

	AFSPRAAK_AFGEZEGD(Level.INFO),

	NIEUWE_AFSPRAAK_AANGEMAAKT(Level.INFO),

	HUISARTSBERICHT_OPNIEUW_VERSTUURD(Level.INFO),

	AFMELDEN(Level.INFO),

	HERAANMELDEN(Level.INFO),

	OVEREENKOMST_MODEL_GEMAAKT(Level.INFO),

	OVEREENKOMST_MODEL_GEWIJZIGD(Level.INFO),

	OVEREENKOMST_MODEL_GEINACTIVEERD(Level.INFO),

	OVEREENKOMST_MODEL_GEACTIVEERD(Level.INFO),

	OVEREENKOMST_TOEGEVOEGD(Level.INFO),

	OVEREENKOMST_GEWIJZIGD(Level.INFO),

	OVEREENKOMST_GEACCODEERD(Level.INFO),

	CLIENT_BEZWAAR_AANGEPAST(Level.INFO),

	CLIENT_BEZWAAR_BRP_INGETROKKEN(Level.INFO),

	CLIENT_OVERDRACHT_PERSOONSGEGEVENS_GEUPLOAD(Level.INFO),

	CLIENT_OVERDRACHT_PERSOONSGEGEVENS_GEDOWNLOAD(Level.INFO),

	PROOF_ONDERZOEK_AFMELDING_START(Level.INFO),

	PROOF_ONDERZOEK_AFMELDING_AFGEROND(Level.INFO),

	PROOF_ONDERZOEK_HERAANMELDING_START(Level.INFO),

	PROOF_ONDERZOEK_HERAANMELDING_AFGEROND(Level.INFO),

	VERWIJDEREN_ONGELDIG_BERICHT(Level.INFO),

	HUISARTS_IMPORT_GESTART(Level.INFO),

	HUISARTS_IMPORT_AFGEROND(Level.INFO),

	HUISARTS_IMPORT_FOUT(Level.ERROR),

	HUISARTS_GEWIJZIGD(Level.INFO),

	HUISARTS_NIET_GEKOPPELD(Level.INFO),

	ANTWOORDFORMULIER_VERWIJDERD(Level.INFO),

	ANTWOORDFORMULIER_VERWIJDERD_GEZET(Level.INFO),

	RETOURZENDINGEN_VERWERKT(Level.INFO, DashboardType.RETOURZENDINGEN, DashboardActieType.START),

	IMPORT_CAP_VERDELING_VERWERKT(Level.INFO),

	SENTINEL_BARCODES_GEWIJZIGD(Level.INFO),

	SENTINEL_ONTVANGEN(Level.INFO),

	SKML_SCHEMA_IMPORT_GESTART(Level.INFO),

	SKML_SCHEMA_IMPORT_AFGEROND(Level.INFO),

	SKML_INTERN_CONTROLE_SET_GEWIJZIGD(Level.INFO),

	INTERNE_TEST_ONTVANGEN(Level.INFO),

	EXTERNE_TEST_ONTVANGEN(Level.INFO),

	INVOERGEN_INTERNE_TEST(Level.INFO),

	INVOERGEN_EXTERNE_TEST(Level.INFO),

	QBASE_BESTAND_GEMAAKT(Level.INFO),

	IFOBT_BESTANDEN_GEAUTORISEERD(Level.INFO),

	IFOBT_BESTANDEN_VERWIJDERD(Level.INFO),

	IFOBT_UITSLAG_DUBBEL(Level.WARNING, DashboardType.IFOBT_VERWERKING, DashboardActieType.OVERIG),

	CONCLUSIE_VASTLEGGEN_WIJZIGEN(Level.INFO),

	COMPLICATIEREGISTER(Level.INFO),

	HUISARTS_BERICHT_VERZONDEN(Level.INFO),

	HUISARTS_BERICHT_NIET_VERZONDEN(Level.ERROR),

	GUNSTIGE_UITSLAG_GESTART(Level.INFO, DashboardType.GUNSTIGE_UITSLAG, DashboardActieType.START),

	GUNSTIGE_UITSLAG_VERSTUURD(Level.INFO, DashboardType.GUNSTIGE_UITSLAG, DashboardActieType.OVERIG),

	GUNSTIGE_UITSLAG_AFGEROND(Level.INFO, DashboardType.GUNSTIGE_UITSLAG, DashboardActieType.OVERIG),

	PROJECT_ALGEMEEN_GESTART(Level.INFO),

	PROJECT_ALGEMEEN_AFGEROND(Level.INFO),

	@Deprecated
	PROJECT_INACTIVEREN_UPLOAD(Level.INFO),

	PROJECT_GROEP_GEPUSHT(Level.INFO),

	UPLOAD_KOPPELRESULTATEN_KANKERREGISTRATIE(Level.INFO),

	TESTEN_VAN_BRIEVEN(Level.INFO),

	CONCLUSIE_VERWIJDEREN(Level.INFO),

	VERVOLG_INTAKE_CONCLUSIE_BATCH_GESTART(Level.INFO, DashboardType.COLON_VERVOLG_INTAKE_CONCLUSIE, DashboardActieType.START),

	VERVOLG_INTAKE_CONCLUSIE_BATCH_AFGEROND(Level.INFO, DashboardType.COLON_VERVOLG_INTAKE_CONCLUSIE, DashboardActieType.OVERIG),

	ENOVATION_HUISARTS_BATCH_GESTART(Level.INFO, DashboardType.ENOVATION_HUISARTSEN, DashboardActieType.START),

	HUISARTS_ONTKOPPELEN_DK_GESTART(Level.INFO, DashboardType.ENOVATION_HUISARTSEN, DashboardActieType.OVERIG),

	HUISARTS_ONTKOPPELEN_DK_AFGEROND(Level.INFO, DashboardType.ENOVATION_HUISARTSEN, DashboardActieType.OVERIG),

	ENOVATION_HUISARTS_BATCH_AFGEROND(Level.INFO, DashboardType.ENOVATION_HUISARTSEN, DashboardActieType.OVERIG),

	BATCH_ADD_TRIGGER(Level.INFO),

	BATCH_REMOVE_TRIGGER(Level.INFO),

	BATCH_START(Level.INFO),

	IFOBT_UITSLAG_VERWIJDERD(Level.INFO),

	COORDINATEN_IMPORT_GESTART(Level.INFO),
	COORDINATEN_IMPORT_AFGEROND(Level.INFO),

	PROJECT_AANGEMAAKT(Level.INFO),

	PROJECT_GEWIJZIGD(Level.INFO),

	@Deprecated
	PROJECT_GROEP_TOEGEVOEGD(Level.INFO),

	PROJECT_GROEP_GEWIJZIGD(Level.INFO),

	PROJECT_GROEP_VERWIJDERD(Level.INFO),

	PROJECT_BRIEF_ACTIE_TOEGEVOEGD(Level.INFO),

	PROJECT_BRIEF_ACTIE_GEWIJZIGD(Level.INFO),

	PROJECT_BRIEF_ACTIE_GEINACTIVEERD(Level.INFO),

	PROJECT_ATTRIBUUT_TOEGEVOEGD(Level.INFO),

	PROJECT_ATTRIBUUT_GEWIJZIGD(Level.INFO),

	PROJECT_ATTRIBUUT_VERWIJDERD(Level.INFO),

	PROJECT_BESTAND_TOEGEVOEGD(Level.INFO),

	PROJECT_UITSLAG_TOEGEVOEGD(Level.INFO),

	PROJECT_BESTAND_VERWERKT_MET_FOUTEN(Level.WARNING),

	PROJECT_BESTAND_VERWERKT(Level.INFO),

	PROJECT_UITSLAG_VERWERKT_MET_FOUTEN(Level.WARNING),

	PROJECT_UITSLAG_VERWERKT(Level.INFO),

	PROJECT_BRIEVEN_BATCH_GESTART(Level.INFO, DashboardType.PROJECT_BRIEVEN_GENEREREN, DashboardActieType.START),

	PROJECT_BRIEVEN_BATCH_AFGEROND(Level.INFO, DashboardType.PROJECT_BRIEVEN_GENEREREN, DashboardActieType.OVERIG),

	PROJECT_BRIEF_MERGE_FOUT(Level.WARNING, DashboardType.PROJECT_BRIEVEN_GENEREREN, DashboardActieType.OVERIG),

	PROJECT_ONVOLLEDIG_ADRES(Level.WARNING, DashboardType.PROJECT_BRIEVEN_GENEREREN, DashboardActieType.OVERIG),

	BRIEFPROJECT_BRIEF_ACTIE_TOEGEVOEGD(Level.INFO),

	BRIEFPROJECT_BRIEF_ACTIE_GEWIJZIGD(Level.INFO),

	BRIEFPROJECT_BRIEF_ACTIE_GEINACTIVEERD(Level.INFO),

	BRIEFPROJECT_AANGEMAAKT(Level.INFO),

	BRIEFPROJECT_GEWIJZIGD(Level.INFO),

	@Deprecated
	BRIEFPROJECT_GROEP_TOEGEVOEGD(Level.INFO),

	BRIEFPROJECT_GROEP_GEWIJZIGD(Level.INFO),

	BRIEFPROJECT_GROEP_VERWIJDERD(Level.INFO),

	VRAGENLIJST_AFGEROND(Level.INFO),

	VRAGENLIJST_OPGESLAGEN(Level.INFO),

	VRAGENLIJST_AFGEWEZEN(Level.INFO),

	SCANDATUM_CORRECTIE_GESTART(Level.INFO),

	SCANDATUM_CORRECTIE_GESTOPT(Level.INFO),

	ADHERENTIE_AANEGEPAST(Level.INFO),

	BEZWAAR_BRIEVEN_BATCH_GESTART(Level.INFO, DashboardType.BEZWAAR_BRIEVEN_GENEREREN, DashboardActieType.START),

	BEZWAAR_BRIEVEN_BATCH_AFGEROND(Level.INFO, DashboardType.BEZWAAR_BRIEVEN_GENEREREN, DashboardActieType.OVERIG),

	BEZWAAR_BRIEF_MERGE_FOUT(Level.WARNING, DashboardType.BEZWAAR_BRIEVEN_GENEREREN, DashboardActieType.OVERIG),

	BEZWAAR_ONVOLLEDIG_ADRES(Level.WARNING, DashboardType.BEZWAAR_BRIEVEN_GENEREREN, DashboardActieType.OVERIG),

	ALGEMENE_BRIEVEN_BATCH_GESTART(Level.INFO, DashboardType.ALGEMENE_BRIEVEN_GENEREREN, DashboardActieType.START),
	ALGEMENE_BRIEVEN_BATCH_AFGEROND(Level.INFO, DashboardType.ALGEMENE_BRIEVEN_GENEREREN, DashboardActieType.OVERIG),
	ALGEMENE_BRIEF_MERGE_FOUT(Level.WARNING, DashboardType.ALGEMENE_BRIEVEN_GENEREREN, DashboardActieType.OVERIG),
	ALGEMENE_BRIEF_ONVOLLEDIG_ADRES(Level.WARNING, DashboardType.ALGEMENE_BRIEVEN_GENEREREN, DashboardActieType.OVERIG),

	SIGNALERING_GENDER_BATCH_GESTART(Level.INFO, DashboardType.SIGNALERING_GENDER, DashboardActieType.START),
	SIGNALERING_GENDER_BATCH_AFGEROND(Level.INFO, DashboardType.SIGNALERING_GENDER, DashboardActieType.OVERIG),

	ILM_ALGEMENE_GEGEVENS_VERWIJDEREN_GESTART(Level.INFO, DashboardType.ILM_ALGEMENE_GEGEVENS_VERWIJDEREN, DashboardActieType.START),

	ILM_ALGEMENE_GEGEVENS_VERWIJDEREN_AFGEROND(Level.INFO, DashboardType.ILM_ALGEMENE_GEGEVENS_VERWIJDEREN, DashboardActieType.OVERIG),

	ILM_ALGEMENE_GEGEVENS_VERWIJDEREN(Level.INFO, DashboardType.ILM_ALGEMENE_GEGEVENS_VERWIJDEREN, DashboardActieType.OVERIG),

	COLON_ONVOLLEDIG_ADRES(Level.WARNING, DashboardType.BRIEVEN_GENEREREN, DashboardActieType.OVERIG),

	BULK_HUISARTSEN_VERWERKING_GESTART(Level.INFO),

	BULK_HUISARTSEN_VERWERKING_AFGEROND(Level.INFO),

	BULK_HUISARTSEN_VERWERKING_MELDING(Level.WARNING),

	WACHTWOORD_VERLOOPT_HERINNERING_GESTART(Level.INFO, DashboardType.WACHTWOORD_VERLOOPT_HERINNERING, DashboardActieType.START),

	WACHTWOORD_VERLOOPT_HERINNERING_AFGEROND(Level.INFO, DashboardType.WACHTWOORD_VERLOOPT_HERINNERING, DashboardActieType.OVERIG),

	WACHTWOORD_VERLOOPT_HERINNERING_VERSTUURD(Level.INFO, DashboardType.WACHTWOORD_VERLOOPT_HERINNERING, DashboardActieType.OVERIG),

	UITSTEL_AANGEVRAAGD(Level.INFO),

	UITSTEL_GEWIJZIGD(Level.INFO),

	VERVANGEN_DOCUMENT(Level.INFO),

	COLON_LIMIET_UITNODIGINGEN(Level.WARNING, DashboardType.CLIENT_SELECTIE, DashboardActieType.OVERIG),

	OPEN_UITNODIGING_REACTIE(Level.INFO),

	OPEN_UITNODIGING_GEMAAKT(Level.INFO),

	UITNODIGING_VERSTUREN_JOB_GESTART(Level.INFO, DashboardType.UITNODIGING_VERSTUREN_NAAR_INPAKCENTRUM, DashboardActieType.START),

	UITNODIGING_VERSTUREN_JOB_AFGEROND(Level.INFO, DashboardType.UITNODIGING_VERSTUREN_NAAR_INPAKCENTRUM, DashboardActieType.OVERIG),

	UITNODIGING_VERSTUREN_NAAR_INPAKCENTRUM_MISLUKT(Level.WARNING, DashboardType.UITNODIGING_VERSTUREN_NAAR_INPAKCENTRUM, DashboardActieType.OVERIG),

	COLON_ADRES_ONVOLLEDIG_VOOR_INPAKCENTRUM(Level.WARNING, DashboardType.UITNODIGING_VERSTUREN_NAAR_INPAKCENTRUM, DashboardActieType.OVERIG),

	INPAKCENTRUM_NIET_BEREIKBAAR(Level.WARNING, DashboardType.UITNODIGING_VERSTUREN_NAAR_INPAKCENTRUM, DashboardActieType.OVERIG),

	CERVIX_BRIEVEN_GENERENEN_GESTART(Level.INFO, DashboardType.CERVIX_BRIEVEN_GENEREREN, DashboardActieType.START),

	CERVIX_BRIEVEN_GENERENEN_AFGEROND(Level.INFO, DashboardType.CERVIX_BRIEVEN_GENEREREN, DashboardActieType.OVERIG),

	CERVIX_BRIEF_MERGE_FOUT(Level.WARNING, DashboardType.CERVIX_BRIEVEN_GENEREREN, DashboardActieType.OVERIG),

	CERVIX_ONVOLLEDIG_ADRES(Level.WARNING, DashboardType.CERVIX_BRIEVEN_GENEREREN, DashboardActieType.OVERIG),

	CERVIX_HUISARTSBERICHTEN_GESTART(Level.INFO, DashboardType.CERVIX_HUISARTSBERICHTEN, DashboardActieType.START),

	CERVIX_HUISARTSBERICHTEN_AFGEROND(Level.INFO, DashboardType.CERVIX_HUISARTSBERICHTEN, DashboardActieType.OVERIG),

	CERVIX_HUISARTSBERICHT_VERZENDEN_MISLUKT(Level.WARNING, DashboardType.CERVIX_HUISARTSBERICHTEN, DashboardActieType.OVERIG),

	CERVIX_ILM_GESTART(Level.INFO, DashboardType.CERVIX_ILM, DashboardActieType.START),

	CERVIX_ILM_AFGEROND(Level.INFO, DashboardType.CERVIX_ILM, DashboardActieType.OVERIG),

	CERVIX_LABFORMULIEREN_INGEZIEN(Level.INFO),

	CERVIX_LABFORMULIER_GESCAND(Level.INFO),

	CERVIX_LABFORMULIER_INGEZIEN(Level.INFO),

	CERVIX_LABFORMULIER_OPGESLAGEN(Level.INFO),

	CERVIX_UITNODIGINGEN_INGEZIEN(Level.INFO),

	CERVIX_UITNODIGING_INGEZIEN(Level.INFO),

	CERVIX_UITNODIGING_OPGESLAGEN(Level.INFO),

	CERVIX_UITSTRIJKJE_BARCODE_AFGEDRUKT(Level.INFO),

	CERVIX_ZAS_BARCODE_AFGEDRUKT(Level.INFO),

	CERVIX_RESULTATEN_MONSTER_VERWIJDERD(Level.INFO),

	CERVIX_GEVOLGEN_LABPROCES_VERWERKEN_GESTART(Level.INFO, DashboardType.CERVIX_GEVOLGEN_LABPROCES_VERWERKEN, DashboardActieType.START),

	CERVIX_ORDER_GESTART(Level.INFO, DashboardType.CERVIX_ORDER, DashboardActieType.START),

	CERVIX_ORDER_AFGEROND(Level.INFO, DashboardType.CERVIX_ORDER, DashboardActieType.OVERIG),

	CERVIX_ORDER_AANMAKEN_MISLUKT(Level.ERROR, DashboardType.CERVIX_ORDER, DashboardActieType.OVERIG),

	CERVIX_ORDER_VERSTUREN_MISLUKT(Level.ERROR, DashboardType.CERVIX_ORDER, DashboardActieType.OVERIG),

	CERVIX_GEVOLGEN_LABPROCES_VERWERKEN_AFGEROND(Level.INFO, DashboardType.CERVIX_GEVOLGEN_LABPROCES_VERWERKEN, DashboardActieType.OVERIG),

	CERVIX_GEVOLGEN_LABPROCES_VERWERKEN_VERVOLG_BEPALEN_MISLUKT(Level.WARNING, DashboardType.CERVIX_GEVOLGEN_LABPROCES_VERWERKEN, DashboardActieType.OVERIG),

	CERVIX_HPV_BERICHT_BINNENGEKOMEN(Level.INFO, DashboardType.CERVIX_HPV_KOPPELING, DashboardActieType.DAG),

	CERVIX_HPV_BERICHT_REJECTED(Level.WARNING, DashboardType.CERVIX_HPV_KOPPELING, DashboardActieType.DAG),

	CERVIX_HPV_ONBEKENDE_BARCODE(Level.WARNING, DashboardType.CERVIX_HPV_KOPPELING, DashboardActieType.DAG),

	CERVIX_HPV_BERICHT_VERWERKT(Level.INFO, DashboardType.CERVIX_HPV_KOPPELING, DashboardActieType.DAG),

	CERVIX_HPV_UITSLAG_OVERSCHREVEN(Level.INFO, DashboardType.CERVIX_HPV_KOPPELING, DashboardActieType.DAG),

	CERVIX_HPV_UITSLAG_GENEGEERD(Level.WARNING, DashboardType.CERVIX_HPV_KOPPELING, DashboardActieType.DAG),

	CERVIX_HPV_UITSLAG_VERWERKT(Level.INFO, DashboardType.CERVIX_HPV_KOPPELING, DashboardActieType.DAG),

	CERVIX_BERICHT_MET_ZELFDE_ID(Level.INFO, DashboardType.CERVIX_VERSLAG_CYTOLOGIE, DashboardActieType.DAG),

	CERVIX_BERICHT_MET_ZELFDE_SETID_VERSIE(Level.INFO, DashboardType.CERVIX_VERSLAG_CYTOLOGIE, DashboardActieType.DAG),

	CERVIX_BERICHT_ONBEKENDE_BSN(Level.WARNING, DashboardType.CERVIX_VERSLAG_CYTOLOGIE, DashboardActieType.DAG),

	CERVIX_BERICHT_ONTVANGEN(Level.INFO, DashboardType.CERVIX_VERSLAG_CYTOLOGIE, DashboardActieType.DAG),

	CERVIX_VERSLAG_CYTOLOGIE_VERWERKT(Level.INFO, DashboardType.CERVIX_VERSLAG_CYTOLOGIE, DashboardActieType.DAG),

	CERVIX_VERSLAG_CYTOLOGIE_VERWERKT_MET_MELDINGEN(Level.WARNING, DashboardType.CERVIX_VERSLAG_CYTOLOGIE, DashboardActieType.DAG),

	CERVIX_VERSLAG_CYTOLOGIE_VERWERKT_MET_ERROR(Level.ERROR, DashboardType.CERVIX_VERSLAG_CYTOLOGIE, DashboardActieType.DAG),

	CERVIX_RONDE_VERLOPEN(Level.INFO, DashboardType.CERVIX_SELECTIE, DashboardActieType.OVERIG),

	CERVIX_CIS_PAP0_UITNODIGINGEN_GEGENEREERD(Level.INFO),

	CERVIX_CIS_PAP0_UITNODIGINGEN_GENEREREN_START(Level.INFO),

	CERVIX_ZAS_UITNODIGING_VERSTUREN_JOB_GESTART(Level.INFO, DashboardType.CERVIX_ZAS_UITNODIGING_VERSTUREN_NAAR_INPAKCENTRUM, DashboardActieType.START),

	CERVIX_ZAS_UITNODIGING_VERSTUREN_JOB_AFGEROND(Level.INFO, DashboardType.CERVIX_ZAS_UITNODIGING_VERSTUREN_NAAR_INPAKCENTRUM, DashboardActieType.OVERIG),

	CERVIX_ZAS_UITNODIGING_VERSTUREN_NAAR_INPAKCENTRUM_MISLUKT(Level.WARNING, DashboardType.CERVIX_ZAS_UITNODIGING_VERSTUREN_NAAR_INPAKCENTRUM, DashboardActieType.OVERIG),

	CERVIX_ADRES_ONVOLLEDIG_VOOR_INPAKCENTRUM(Level.WARNING, DashboardType.CERVIX_ZAS_UITNODIGING_VERSTUREN_NAAR_INPAKCENTRUM, DashboardActieType.OVERIG),

	CERVIX_ZAS_INPAKCENTRUM_NIET_BEREIKBAAR(Level.WARNING, DashboardType.CERVIX_ZAS_UITNODIGING_VERSTUREN_NAAR_INPAKCENTRUM, DashboardActieType.OVERIG),

	CERVIX_ZAS_CONTROLE_KOPPELEN_GESTART(Level.INFO, DashboardType.CERVIX_ZAS_CONTROLE_TERUGKOPPELING, DashboardActieType.START),

	CERVIX_ZAS_CONTROLE_KOPPELEN_AFGEROND(Level.INFO, DashboardType.CERVIX_ZAS_CONTROLE_TERUGKOPPELING, DashboardActieType.OVERIG),

	CERVIX_ZAS_CONTROLE_KOPPELEN_FOUT(Level.ERROR, DashboardType.CERVIX_ZAS_CONTROLE_TERUGKOPPELING, DashboardActieType.OVERIG),

	CERVIX_ZAS_KOPPELEN_GESTART(Level.INFO, DashboardType.CERVIX_ZAS_TERUGKOPPELING, DashboardActieType.START),

	CERVIX_ZAS_KOPPELEN_AFGEROND(Level.INFO, DashboardType.CERVIX_ZAS_TERUGKOPPELING, DashboardActieType.OVERIG),

	CERVIX_ZAS_AANGEVRAAGD(Level.INFO),

	REGIO_BRIEVEN_GENERENEN_GESTART(Level.INFO, DashboardType.REGIO_BRIEVEN_GENEREREN, DashboardActieType.START),

	REGIO_BRIEVEN_GENERENEN_AFGEROND(Level.INFO, DashboardType.REGIO_BRIEVEN_GENEREREN, DashboardActieType.OVERIG),

	REGIO_BRIEF_MERGE_FOUT(Level.WARNING, DashboardType.REGIO_BRIEVEN_GENEREREN, DashboardActieType.OVERIG),

	CERVIX_CISMIGRATIE_ONGESTRUCTUREERD_GESTART(Level.INFO),

	CERVIX_CISMIGRATIE_ONGESTRUCTUREERD_AFGEROND(Level.INFO),

	CERVIX_CISMIGRATIE_GESTRUCTUREERD_GESTART(Level.INFO),

	CERVIX_CISMIGRATIE_GESTRUCTUREERD_AFGEROND(Level.INFO),

	CERVIX_FOUT_RETOURADRES_BMHK_LAB(Level.WARNING, DashboardType.CERVIX_ZAS_UITNODIGING_VERSTUREN_NAAR_INPAKCENTRUM, DashboardActieType.OVERIG),

	CERVIX_NA_GBA_VERWERKING_GESTART(Level.INFO, DashboardType.CERVIX_BATCH_NA_GBA_VERWERKING, DashboardActieType.START),

	CERVIX_NA_GBA_VERWERKING_AFGEROND(Level.INFO, DashboardType.CERVIX_BATCH_NA_GBA_VERWERKING, DashboardActieType.OVERIG),

	CERVIX_BEPALEN_VERRICHTINGEN_START(Level.INFO, DashboardType.CERVIX_BEPALEN_VERRICHTINGEN, DashboardActieType.START),

	CERVIX_BEPALEN_VERRICHTINGEN_AFGEROND(Level.INFO, DashboardType.CERVIX_BEPALEN_VERRICHTINGEN, DashboardActieType.OVERIG),

	CERVIX_HPV_ORU_BERICHTEN_START(Level.INFO, DashboardType.CERVIX_HPV_ORU, DashboardActieType.START),

	CERVIX_HPV_ORU_BERICHTEN_AFGEROND(Level.INFO, DashboardType.CERVIX_HPV_ORU, DashboardActieType.OVERIG),

	CERVIX_HPV_ORU_BERICHTEN_VERSTUREN_MISLUKT(Level.ERROR, DashboardType.CERVIX_HPV_ORU, DashboardActieType.OVERIG),

	CERVIX_HPVMIN_UITSLAGEN_VERWIJDEREN_START(Level.INFO, DashboardType.CERVIX_HPVMIN_UITSLAGEN_VERWIJDEREN, DashboardActieType.START),

	CERVIX_HPVMIN_UITSLAGEN_VERWIJDEREN_AFGEROND(Level.INFO, DashboardType.CERVIX_HPVMIN_UITSLAGEN_VERWIJDEREN, DashboardActieType.OVERIG),

	CERVIX_HEROVERWEGERSBRIEF_AANGEMAAKT(Level.INFO),

	CERVIX_LAB_TARIEF_AANGEMAAKT(Level.INFO),

	CERVIX_LAB_TARIEF_VERWIJDERD(Level.INFO),

	CERVIX_LAB_TARIEF_INDEXEERD(Level.INFO),

	CERVIX_HUISARTS_TARIEF_AANGEMAAKT(Level.INFO),

	CERVIX_HUISARTS_TARIEF_VERWIJDERD(Level.INFO),

	CERVIX_HUISARTS_TARIEF_INDEXEERD(Level.INFO),

	CERVIX_HUISARTSLOCATIE_VERWIJDERD(Level.INFO),

	CERVIX_EXPORTEER_BETAALOPDRACHT(Level.INFO),

	CERVIX_BETAALOPDRACHT_VERWIJDERD(Level.INFO),

	CERVIX_SEPA_DOCUMENT_GEDOWNLOAD(Level.INFO),

	CERVIX_SEPA_SPECIFICATIE_DOCUMENT_GEDOWNLOAD(Level.INFO),

	CERVIX_BETALING_GENEREREN_IBAN_FOUT(Level.WARNING, DashboardType.CERVIX_BEPALEN_VERRICHTINGEN, DashboardActieType.OVERIG),

	CERVIX_LABFORMULIER_GENEREREN_IBAN_FOUT(Level.WARNING, DashboardType.REGIO_BRIEVEN_GENEREREN, DashboardActieType.OVERIG),

	CERVIX_CISMIGRANTEN_UITNODIGEN_FOUT(Level.WARNING),

	CERVIX_ZORGMAIL_VERIFICATIE_HUISARTSBERICHT_VERSTUURD(Level.INFO, DashboardType.CERVIX_HUISARTSBERICHTEN, DashboardActieType.DAG),

	CERVIX_ZORGMAIL_VERIFICATIE_HUISARTSBERICHT_VERSTUREN_MISLUKT(Level.WARNING, DashboardType.CERVIX_HUISARTSBERICHTEN, DashboardActieType.DAG),

	CERVIX_HL7V2_BERICHT_VERSTUREN_MISLUKT(Level.ERROR, DashboardType.CERVIX_HL7V2_KOPPELINGEN, DashboardActieType.DAG),

	CERVIX_HL7V2_BERICHT_QUEUE_ERG_GROOT(Level.WARNING, DashboardType.CERVIX_HL7V2_KOPPELINGEN, DashboardActieType.DAG),

	CERVIX_HL7V2_BERICHT_QUEUE_NORMAAL(Level.INFO, DashboardType.CERVIX_HL7V2_KOPPELINGEN, DashboardActieType.DAG),

	CERVIX_HL7V2_BERICHT_VERBINDING_HERSTELD(Level.INFO, DashboardType.CERVIX_HL7V2_KOPPELINGEN, DashboardActieType.DAG),

	CERVIX_HL7V2_BERICHT_BATCH_GESTOPT(Level.ERROR, DashboardType.CERVIX_HL7V2_KOPPELINGEN, DashboardActieType.DAG),
	CERVIX_MAIL_VERSTUURD(Level.INFO),

	@Deprecated(since = "Vervallen met ingebruikname van Mailqueue", forRemoval = true)
	CERVIX_MAIL_VERSTUREN_MISLUKT(Level.INFO),

	MAMMA_AFSPRAAK_DREMPEL_GEWIJZIGD(Level.INFO),

	MAMMA_STANDPLAATS(Level.INFO),

	MAMMA_SCREENINGS_EENHEID(Level.INFO),

	MAMMA_MAMMOGRAAF(Level.INFO),

	MAMMA_TEHUIS_BEHEER(Level.INFO),

	MAMMA_TEHUIS_ONTKOPPELD(Level.INFO),

	MAMMA_TEHUIS_UITGENODIGD(Level.INFO),

	MAMMA_POSTCODE_REEKS(Level.INFO),

	MAMMA_CAPACITEIT(Level.INFO),

	MAMMA_BLOKKADE(Level.INFO),

	PROJECTCLIENT_GEINACTIVEERD(Level.INFO),

	MAMMA_RONDE_VERLOPEN(Level.INFO, null, DashboardActieType.OVERIG),

	MAMMA_DOSSIERGEGEVENS_GEWIJZIGD(Level.INFO),

	MAMMA_WERKLIJST_INGEZIEN(Level.INFO),

	MAMMA_BEOORDELING_INGEZIEN(Level.INFO),

	MAMMA_BEOORDELING_AFGEROND(Level.INFO),

	MAMMA_BEOORDELING_SIGNALERING_GETOOND(Level.INFO),

	MAMMA_BEOORDELINGEN_GEACCORDEERD(Level.INFO),

	MAMMA_DISCREPANTIE_BEOORDELINGEN_DOORZETTEN(Level.INFO),

	MAMMA_BRIEVEN_GENEREREN_GESTART(Level.INFO, DashboardType.MAMMA_BRIEVEN_GENEREREN, DashboardActieType.START),

	MAMMA_BRIEVEN_GENEREREN_AFGEROND(Level.INFO, DashboardType.MAMMA_BRIEVEN_GENEREREN, DashboardActieType.OVERIG),

	MAMMA_BRIEVEN_GENEREREN_ERROR(Level.ERROR, DashboardType.MAMMA_BRIEVEN_GENEREREN, DashboardActieType.OVERIG),

	MAMMA_BRIEF_MERGE_FOUT(Level.WARNING, DashboardType.BRIEVEN_GENEREREN, DashboardActieType.OVERIG),

	MAMMA_ONVOLLEDIG_ADRES(Level.WARNING, DashboardType.MAMMA_BRIEVEN_GENEREREN, DashboardActieType.OVERIG),

	MAMMA_CONCEPT_MODEL_RESET_GESTART(Level.INFO),

	MAMMA_CONCEPT_MODEL_RESET_AFGEROND(Level.INFO),

	MAMMA_UITNODIGEN_GESTART(Level.INFO, DashboardType.MAMMA_UITNODIGINGEN, DashboardActieType.START),

	MAMMA_UITNODIGEN_AFGEROND(Level.INFO, DashboardType.MAMMA_UITNODIGINGEN, DashboardActieType.OVERIG),

	MAMMA_UITNODIGEN_FOUT(Level.ERROR, DashboardType.MAMMA_UITNODIGINGEN, DashboardActieType.OVERIG),

	MAMMA_UITNODIGEN_ONDERBROKEN(Level.WARNING, DashboardType.MAMMA_UITNODIGINGEN, DashboardActieType.OVERIG),

	MAMMA_BEOORDELINGEN_GEACCORDEERD_GESTART(Level.INFO),

	MAMMA_BEOORDELINGEN_GEACCORDEERD_AFGEROND(Level.INFO),

	MAMMA_DISCREPANTIE_BEOORDELINGEN_DOORZETTEN_GESTART(Level.INFO),

	MAMMA_DISCREPANTIE_BEOORDELINGEN_DOORZETTEN_AFGEROND(Level.INFO),

	MAMMA_UITSTEL(Level.INFO),

	MAMMA_ONVOLLEDIG_ZONDER_FOTOS_TOCH_IMS_BEELDEN(Level.INFO),

	MAMMA_BEOORDELING_OPGESCHORT(Level.INFO),

	MAMMA_ACHTERVANG_UITSTEL(Level.INFO),

	MAMMA_MINDER_VALIDE_UITWIJK(Level.INFO),

	MAMMA_UITSTEL_GEANNULEERD_TEHUIS(Level.INFO),

	MAMMA_AFSPRAAK_VERZET(Level.INFO),

	MAMMA_AFSPRAAK_GEFORCEERD(Level.INFO),

	MAMMA_ONVOLDOENDE_VRIJE_CAPACITEIT(Level.WARNING, DashboardType.MAMMA_UITNODIGINGEN, DashboardActieType.OVERIG),

	MAMMA_DOELGROEP_GEWIJZIGD(Level.INFO),

	MAMMA_NA_GBA_GESTART(Level.INFO, DashboardType.MAMMA_BATCH_NA_GBA_VERWERKING, DashboardActieType.START),

	MAMMA_NA_GBA_AFGEROND(Level.INFO, DashboardType.MAMMA_BATCH_NA_GBA_VERWERKING, DashboardActieType.OVERIG),

	MAMMA_ONTBREKENDE_POSTCODEREEKS(Level.WARNING, DashboardType.MAMMA_BATCH_NA_GBA_VERWERKING, DashboardActieType.OVERIG),

	MAMMA_CLIENT_ZONDER_POSTCODE(Level.WARNING, DashboardType.MAMMA_BATCH_NA_GBA_VERWERKING, DashboardActieType.OVERIG),

	MAMMA_HERINNEREN_GESTART(Level.INFO, DashboardType.MAMMA_HERINNEREN, DashboardActieType.START),

	MAMMA_HERINNEREN_AFGEROND(Level.INFO, DashboardType.MAMMA_HERINNEREN, DashboardActieType.OVERIG),

	MAMMA_SE_WEBSOCKET_VERBINDING_GEMAAKT(Level.INFO),

	MAMMA_SE_WEBSOCKET_VERBINDING_VERLOREN(Level.INFO),

	MAMMA_SE_DAGLIJST_ERROR(Level.ERROR),

	MAMMA_SE_DAGLIJST_OPBOUWEN_ERROR(Level.ERROR),

	MAMMA_SE_INSCHRIJVEN(Level.INFO),

	MAMMA_SE_CODE_OPHALEN_MET_IPADRES(Level.WARNING),

	MAMMA_SE_ONDERZOEK_STARTEN(Level.INFO),

	MAMMA_SE_ONDERZOEK_UITGEVOERD(Level.INFO),

	MAMMA_SE_ONDERZOEK_ONDERBROKEN(Level.WARNING),

	MAMMA_SE_ONDERZOEK_ONVOLLEDIG(Level.WARNING),

	MAMMA_SE_ONDERZOEK_AFGEROND(Level.INFO),

	MAMMA_SE_ONDERZOEK_DOORGEVOERD(Level.INFO),

	MAMMA_SE_INSCHRIJVEN_PASSANT(Level.INFO),

	MAMMA_SE_UITSCHRIJVEN(Level.INFO),

	MAMMA_SE_START_KWALITEITSOPNAME(Level.INFO),

	MAMMA_SE_BEEINDIG_KWALITEITSOPNAME(Level.INFO),

	MAMMA_SE_LRCB_MEEKIJKVERZOEK(Level.INFO),

	MAMMA_OUDE_BEELDEN_OPGEHAALD_OP_SE(Level.INFO),

	MAMMA_GEEN_MPPS_ONTVANGEN_SE(Level.WARNING),

	MAMMA_VERSCHIL_BEELDEN_ANNOTATIE_AMPUTATIE_SE(Level.INFO),

	MAMMA_CE_VERSLAG_GOEDKEUREN(Level.INFO),

	MAMMA_CE_VERSLAG_AFKEUREN(Level.INFO),

	MAMMA_CE_VERSLAG_GOEDKEURING_OPGESCHORT(Level.INFO),

	MAMMA_CE_ONBEOORDEELBAAR_AFGEHANDELD(Level.INFO),

	MAMMA_VERSLAG_VERZENDEN_AAN_HUISARTS(Level.INFO),

	MAMMA_HL7_BERICHT_BATCH_GESTOPT(Level.ERROR, DashboardType.MAMMA_IMS_UITGAAND, DashboardActieType.DAG),

	MAMMA_HL7_BERICHT_VERSTUREN_MISLUKT(Level.ERROR, DashboardType.MAMMA_IMS_UITGAAND, DashboardActieType.DAG),

	MAMMA_HL7_BERICHT_VERBINDING_HERSTELD(Level.INFO, DashboardType.MAMMA_IMS_UITGAAND, DashboardActieType.DAG),

	MAMMA_HL7_BERICHT_ONTVANGEN_MISLUKT(Level.INFO, DashboardType.MAMMA_IMS_INKOMEND, DashboardActieType.DAG),

	MAMMA_HL7_BERICHT_ERROR_ONTVANGEN(Level.WARNING, DashboardType.MAMMA_IMS_INKOMEND, DashboardActieType.DAG),

	MAMMA_HL7_BERICHT_AL_ONTVANGEN(Level.WARNING, DashboardType.MAMMA_IMS_INKOMEND, DashboardActieType.DAG),

	MAMMA_HL7_BERICHT_QUEUE_ERG_GROOT(Level.WARNING, DashboardType.MAMMA_IMS_UITGAAND, DashboardActieType.DAG),

	MAMMA_HL7_BERICHT_QUEUE_NORMAAL(Level.INFO, DashboardType.MAMMA_IMS_UITGAAND, DashboardActieType.DAG),

	MAMMA_HL7_BERICHT_BEELDEN_VERWIJDERD(Level.INFO, DashboardType.MAMMA_IMS_INKOMEND, DashboardActieType.DAG),

	MAMMA_HUISARTSBERICHTEN_OPNIEUW_VERSTUREN_GESTART(Level.INFO, DashboardType.MAMMA_HUISARTS_BERICHTEN, DashboardActieType.START),

	MAMMA_HUISARTSBERICHTEN_OPNIEUW_VERSTUREN_AFGEROND(Level.INFO, DashboardType.MAMMA_HUISARTS_BERICHTEN, DashboardActieType.OVERIG),

	MAMMA_HUISARTSBERICHTEN_VERZONDEN(Level.INFO, DashboardType.MAMMA_HUISARTS_BERICHTEN, DashboardActieType.DAG),

	MAMMA_HUISARTSBERICHTEN_NIET_VERZONDEN(Level.ERROR, DashboardType.MAMMA_HUISARTS_BERICHTEN, DashboardActieType.DAG),

	MAMMA_KANSBEREKENING_GESTART(Level.INFO, DashboardType.MAMMA_KANSBEREKENING, DashboardActieType.START),

	MAMMA_KANSBEREKENING_AFGEROND(Level.INFO, DashboardType.MAMMA_KANSBEREKENING, DashboardActieType.OVERIG),

	MAMMA_VERVOLG_ONDERZOEKEN_GESTART(Level.INFO, DashboardType.MAMMA_VERVOLG_ONDERZOEKEN, DashboardActieType.START),

	MAMMA_VERVOLG_ONDERZOEKEN_AFGEROND(Level.INFO, DashboardType.MAMMA_VERVOLG_ONDERZOEKEN, DashboardActieType.OVERIG),

	MAMMA_AFSPRAAK_GEANNULEERD(Level.INFO),

	MAMMA_GEEN_BEELDEN_ONTVANGEN(Level.ERROR, DashboardType.MAMMA_VERVOLG_ONDERZOEKEN, DashboardActieType.OVERIG),

	MAMMA_ONDERZOEK_NIET_AFGESLOTEN(Level.ERROR, DashboardType.MAMMA_VERVOLG_ONDERZOEKEN, DashboardActieType.OVERIG),

	MAMMA_BE_IMS_ERROR_ONBEKEND(Level.INFO),

	MAMMA_BE_IMS_WS_FOUT(Level.INFO),

	MAMMA_BE_IMS_HTTP_FOUT(Level.INFO),

	MAMMA_UITWISSELPORTAAL_START(Level.INFO, DashboardType.MAMMA_UITWISSELPORTAAL, DashboardActieType.START),

	MAMMA_UITWISSELPORTAAL_AFGEROND(Level.INFO, DashboardType.MAMMA_UITWISSELPORTAAL, DashboardActieType.OVERIG),

	MAMMA_UITWISSELPORTAAL_DOWNLOAD(Level.INFO),

	MAMMA_CE_RADIOLOOG_TOEGEWEZEN_AAN_VERSLAGLEZING(Level.INFO),

	MAMMA_ILM_GESTART(Level.INFO, DashboardType.MAMMA_ILM, DashboardActieType.START),

	MAMMA_ILM_AFGEROND(Level.INFO, DashboardType.MAMMA_ILM, DashboardActieType.OVERIG),

	MAMMA_ILM_STATUS_GEFORCEERD(Level.INFO),

	MAMMA_XDS_BATCH_JOB_GESTART(Level.INFO),

	MAMMA_XDS_BATCH_JOB_GESTOPT(Level.INFO),

	MAMMA_BERICHT_ONTVANGEN(Level.INFO, DashboardType.MAMMA_VERSLAG_FOLLOW_UP, DashboardActieType.DAG),

	MAMMA_VERSLAG_FOLLOW_UP_VERWERKT(Level.INFO, DashboardType.MAMMA_VERSLAG_FOLLOW_UP, DashboardActieType.DAG),

	MAMMA_VERSLAG_FOLLOW_UP_VERWERKT_MET_MELDING(Level.WARNING, DashboardType.MAMMA_VERSLAG_FOLLOW_UP, DashboardActieType.DAG),

	MAMMA_VERSLAG_FOLLOW_UP_VERWERKT_MET_ERROR(Level.ERROR, DashboardType.MAMMA_VERSLAG_FOLLOW_UP, DashboardActieType.DAG),

	MAMMA_VERSLAG_FOLLOW_UP_VAST(Level.INFO),

	MAMMA_VERSLAG_FOLLOW_UP_WIJZIG(Level.INFO),

	MAMMA_VERSLAG_FOLLOW_UP_VERWIJDERD(Level.INFO),

	MAMMA_VERSLAG_FOLLOW_UP_HEROPEND(Level.INFO),

	MAMMA_FOLLOW_UP_CONCLUSIE(Level.INFO),

	MAMMA_FOLLOW_UP_PA_NIET_TE_VERWACHTEN(Level.INFO),

	MAMMA_RADIOLOGIE_VERSLAG_OPGESLAGEN(Level.INFO),

	MAMMA_BERICHT_MET_ZELFDE_ID(Level.INFO, DashboardType.MAMMA_VERSLAG_FOLLOW_UP, DashboardActieType.DAG),

	MAMMA_BERICHT_MET_ZELFDE_SETID_VERSIE(Level.INFO, DashboardType.MAMMA_VERSLAG_FOLLOW_UP, DashboardActieType.DAG),

	MAMMA_BERICHT_ONBEKENDE_BSN(Level.INFO, DashboardType.MAMMA_VERSLAG_FOLLOW_UP, DashboardActieType.DAG),

	MAMMA_UPLOAD_VERZOEK(Level.INFO),

	MAMMA_PALGA_CSV_EXPORT_GESTART(Level.INFO, DashboardType.MAMMA_PALGA_CSV_EXPORT, DashboardActieType.START),

	MAMMA_PALGA_CSV_EXPORT_AFGEROND(Level.INFO, DashboardType.MAMMA_PALGA_CSV_EXPORT, DashboardActieType.OVERIG),

	MAMMA_PALGA_CSV_EXPORT(Level.INFO),

	MAMMA_PALGA_CSV_IMPORT_GESTART(Level.INFO, DashboardType.MAMMA_PALGA_CSV_IMPORT, DashboardActieType.START),

	MAMMA_PALGA_CSV_IMPORT_AFGEROND(Level.INFO, DashboardType.MAMMA_PALGA_CSV_IMPORT, DashboardActieType.OVERIG),

	MAMMA_PALGA_CSV_IMPORT(Level.INFO),

	MAMMA_AFSPRAAK_AFGEMELD_SE_OFFLINE(Level.WARNING, DashboardType.MAMMA_SE_BERICHTEN, DashboardActieType.DAG),

	MAMMA_GEFAALDE_TRANSACTIE_SE(Level.ERROR, DashboardType.MAMMA_SE_BERICHTEN, DashboardActieType.DAG),

	MAMMA_PLANNING_CONCEPT_OPGESLAGEN(Level.INFO),

	MAMMA_CONTROLE_MISSENDE_UITSLAGEN_GESTART(Level.INFO, DashboardType.MAMMA_CONTROLE_MISSENDE_UITSLAGEN, DashboardActieType.START),

	MAMMA_CONTROLE_MISSENDE_UITSLAGEN_MATCH(Level.WARNING, DashboardType.MAMMA_CONTROLE_MISSENDE_UITSLAGEN, DashboardActieType.OVERIG),

	MAMMA_CONTROLE_MISSENDE_UITSLAGEN_MATCH_GECONTROLEERD(Level.INFO),

	MAMMA_CONTROLE_MISSENDE_UITSLAGEN_AFGEROND(Level.INFO, DashboardType.MAMMA_CONTROLE_MISSENDE_UITSLAGEN, DashboardActieType.OVERIG),

	MAMMA_ONDERZOEKTYPE_GEWIJZIGD(Level.INFO),

	MAMMA_DIGITAAL_CONTACT_SMS_VERSTUREN_GEFAALD(Level.WARNING),
	;

	private final Level defaultLevel;

	private final DashboardType type;

	private final DashboardActieType dashboardType;

	private LogGebeurtenis(Level defaultLevel)
	{
		this.defaultLevel = defaultLevel;
		this.type = null;
		this.dashboardType = null;
	}

	private LogGebeurtenis(Level defaultLevel, DashboardType item, DashboardActieType dashboardType)
	{
		this.defaultLevel = defaultLevel;
		this.type = item;
		this.dashboardType = dashboardType;
	}

	public Level getDefaultLevel()
	{
		return defaultLevel;
	}

	public DashboardType getDashboardType()
	{
		return type;
	}

	public DashboardActieType getDashboardActieType()
	{
		return dashboardType;
	}

}
