# Dit bestand wordt gebruikt voor productie (via Docker file), dus zorg dat waardes hier goed staan voor productie!
debug: false
server:
  port: 8080

spring:
  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.xml
  datasource:
    url: jdbc:sqlite:db/screenit-se.db
    driver-class-name: org.sqlite.JDBC

SE_REST_URL: http://localhost:14831
ENVIRONMENT: Productie
DISABLE_NFC_AUTHENTICATION: false
MAX_MINUTEN_WACHTTIJD_GEGEVENS_OPHAAL_JOB: 10
